[versions]
micronaut-docs = "2.0.0"
micronaut = "4.0.0-M1"

micronaut-security = "4.0.0-SNAPSHOT"
micronaut-test = "4.0.0-SNAPSHOT"

managed-elasticsearch = "7.16.3"

graal-svm = "22.3.1"
groovy = "4.0.9"
spock = "2.3-groovy-4.0"
testcontainers = "1.17.6"

[libraries]
micronaut-security = { module = "io.micronaut.security:micronaut-security-bom", version.ref = "micronaut-security" }

managed-elasticsearch-java = { module = "co.elastic.clients:elasticsearch-java", version.ref = "managed-elasticsearch" }
managed-elasticsearch-rest-high-level-client = { module = "org.elasticsearch.client:elasticsearch-rest-high-level-client", version.ref = "managed-elasticsearch" }

graal-svm = { module = "org.graalvm.nativeimage:svm", version.ref = "graal-svm" }

testcontainers-elasticsearch = { module = "org.testcontainers:elasticsearch", version.ref = "testcontainers"  }

